#!/bin/bash

set -e

REPO_NAME="java-github-actions-demo"

echo "Creating project: $REPO_NAME"

# Root directory
mkdir -p "$REPO_NAME"
cd "$REPO_NAME"

# GitHub Actions
mkdir -p .github/workflows

# Main source
mkdir -p src/main/java/com/company/demo

# Resources
mkdir -p src/main/resources

# Test source
mkdir -p src/test/java/com/company/demo

# Target folders (normally generated by Maven)
mkdir -p target/classes
mkdir -p target/test-classes
mkdir -p target/maven-status

# Workflow
touch .github/workflows/ci.yml

# Java files
touch src/main/java/com/company/demo/Application.java
touch src/main/java/com/company/demo/GreetingService.java
touch src/main/java/com/company/demo/Employee.java
touch src/main/java/com/company/demo/VersionInfo.java
touch src/main/java/com/company/demo/DatabaseConfig.java
touch src/main/java/com/company/demo/HealthCheck.java
touch src/main/java/com/company/demo/BuildInfo.java
touch src/main/java/com/company/demo/Utils.java

# Resource files
touch src/main/resources/application.properties
touch src/main/resources/banner.txt

# Test files
touch src/test/java/com/company/demo/GreetingServiceTest.java
touch src/test/java/com/company/demo/EmployeeTest.java
touch src/test/java/com/company/demo/HealthCheckTest.java

# Root files
touch pom.xml
touch README.md
touch LICENSE
touch .gitignore
touch mvnw

echo ""
echo "Repository structure created successfully."
echo ""

tree